title: CN Palermo
author: Alessandro Romancino, Salvatore Micciché
copyright: "2023"
logo: images/cnpa_banner_alt.png

html:
  favicon: images/cnpa_logo.png
  use_repository_button: true
  home_page_in_navbar: false

repository:
  url: https://github.com/CNPalermo/complex-networks-palermo
  branch: main

# launch_buttons:
#   notebook_interface: "classic"
#   binderhub_url: "https://mybinder.org"
#   thebe: true

only_build_toc_files: true
execute:
  execute_notebooks: "off"

bibtex_bibfiles:
  - references.bib

parse:
  myst_enable_extensions:
    - smartquotes
    - amsmath
    - dollarmath
    - colon_fence
    - html_image
    - tasklist
    - linkify

sphinx:
  config:
    bibtex_reference_style: author_year
