title: CN Palermo
author: Alessandro Romancino, Salvatore Micciché
copyright: "2023"

logo: images/cnpa_banner.png

html:
  favicon: images/cnpa_logo.png
  # use_repository_button: true

only_build_toc_files: true
execute:
  execute_notebooks: "off"

bibtex_bibfiles:
  - references.bib

parse:
  myst_enable_extensions:
    - smartquotes
    - amsmath
    - dollarmath
    - colon_fence
    - html_image
    - tasklist
    - linkify

sphinx:
  config:
    bibtex_reference_style: author_year

# Information about where the book exists on the web
# repository:
#   url: https://github.com/executablebooks/jupyter-book  # Online location of your book
#   path_to_book: docs  # Optional path to your book, relative to the repository root
#   branch: master  # Which branch of the repository should be used when creating links (optional)
